workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Generate Android platform
        script: |
          flutter create --platforms=android --org com.varshaforgings .
          mkdir -p android/app
          cp google-services.json android/app/google-services.json
      - name: Get packages
        script: flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
